build: change github actions
using workflow from https://github.com/SpectralOps/rust-ci-release-template

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,145 +1,216 @@
 name: Release
-
 on:
+  # schedule:
+  # - cron: '0 0 * * *' # midnight UTC
+
   push:
     tags:
-      - v*
+      - "v[0-9]+.[0-9]+.[0-9]+"
+    ## - release
 
 env:
-  CARGO_TERM_COLOR: always
+  BIN_NAME1: caliph
+  BIN_NAME2: conph
+  PROJECT_NAME: caliph
+  REPO_NAME: pdunne/rust-ci-release-template
+  BREW_TAP: pdunne/homebrew-tap
 
 jobs:
-  publish-crate:
-    name: Publish Crate
-    runs-on: ubuntu-20.04
-    steps:
-    - name: Clone
-      uses: actions/checkout@v2
-    - name: Cache
-      uses: actions/cache@v2
-      with:
-        path: |
-          ~/.cargo/registry
-          ~/.cargo/git
-          ~/.rustup
-          target
-        key: ${{ runner.os }}-stable
-    - name: Setup
-      run: |
-        rustup install stable
-    - name: Build
-      run: cargo build --verbose
-    - name: Run tests
-      run: cargo test
-    - name: Publish
-      run: cargo publish
-      env:
-        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
-
-  publish-to-github:
-    name: Publish to Github
-    runs-on: ${{matrix.os}}
+  dist:
+    name: Dist
+    runs-on: ${{ matrix.os }}
     strategy:
+      fail-fast: false # don't fail other jobs if one fails
       matrix:
+        build: [x86_64-linux, aarch64-linux, x86_64-macos, x86_64-windows] #, x86_64-win-gnu, win32-msvc
         include:
-        - build: linux
-          os: ubuntu-latest
-          rust: stable
-          target: x86_64-unknown-linux-musl
-          cross: false
-        - build: arm-v7
-          os: ubuntu-latest
-          rust: stable
-          target: armv7-unknown-linux-gnueabihf
-          linker: gcc-arm-linux-gnueabihf
-          cross: true
-        - build: aarch64
-          os: ubuntu-latest
-          rust: stable
-          target: aarch64-unknown-linux-gnu
-          linker: gcc-aarch64-linux-gnu
-          cross: true
-        - build: macos
-          os: macos-latest
-          rust: stable
-          target: x86_64-apple-darwin
-          cross: false
+          - build: x86_64-linux
+            os: ubuntu-20.04
+            rust: stable
+            target: x86_64-unknown-linux-gnu
+            cross: false
+          - build: aarch64-linux
+            os: ubuntu-20.04
+            rust: stable
+            target: aarch64-unknown-linux-gnu
+            cross: true
+          - build: x86_64-macos
+            os: macos-latest
+            rust: stable
+            target: x86_64-apple-darwin
+            cross: false
+          - build: x86_64-windows
+            os: windows-2019
+            rust: stable
+            target: x86_64-pc-windows-msvc
+            cross: false
+        # - build: aarch64-macos
+        #   os: macos-latest
+        #   rust: stable
+        #   target: aarch64-apple-darwin
+        # - build: x86_64-win-gnu
+        #   os: windows-2019
+        #   rust: stable-x86_64-gnu
+        #   target: x86_64-pc-windows-gnu
+        # - build: win32-msvc
+        #   os: windows-2019
+        #   rust: stable
+        #   target: i686-pc-windows-msvc
+
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v2
-      with:
-        fetch-depth: 1
+      - name: Checkout sources
+        uses: actions/checkout@v2
+        with:
+          submodules: true
 
-    - name: Cache
-      uses: actions/cache@v2
-      with:
-        path: |
-          ~/.cargo/registry
-          ~/.cargo/git
-          ~/.rustup
-          target
-        key: ${{ runner.os }}-${{ matrix.rust }}
+      - name: Install ${{ matrix.rust }} toolchain
+        uses: actions-rs/toolchain@v1
+        with:
+          profile: minimal
+          toolchain: ${{ matrix.rust }}
+          target: ${{ matrix.target }}
+          override: true
 
-    - name: Install Linker
-      if: matrix.cross
-      run: |
-        sudo apt update
-        sudo apt install ${{ matrix.linker }}
-        cat .cargo/config.github >> .cargo/config
+      - name: Run cargo test
+        uses: actions-rs/cargo@v1
+        with:
+          use-cross: ${{ matrix.cross }}
+          command: test
+          args: --release --locked --target ${{ matrix.target }}
 
-    - name: Install Rust
-      run: |
-        rustup install ${{ matrix.rust }}
-        rustup target add ${{ matrix.target }}
-        rustup show
+      - name: Build release binary
+        uses: actions-rs/cargo@v1
+        with:
+          use-cross: ${{ matrix.cross }}
+          command: build
+          args: --release --locked --target ${{ matrix.target }}
 
-    - name: Build
-      run: cargo build --release --target ${{ matrix.target }}
+      - name: Strip release binary (linux and macos)
+        if: matrix.build == 'x86_64-linux' || matrix.build == 'x86_64-macos'
+        run: |
+          strip "target/${{ matrix.target }}/release/$BIN_NAME1
+          strip "target/${{ matrix.target }}/release/$BIN_NAME2
 
-    - name: Package Artifacts
-      run: |
-        src=$(pwd)
-        stage=
-        case $RUNNER_OS in
-            Linux)
-                stage=$(mktemp -d)
-                ;;
-            macOS)
-                stage=$(mktemp -d -t tmp)
-                ;;
-        esac
+      - name: Strip release binary (arm)
+        if: matrix.build == 'aarch64-linux'
+        run: |
+          docker run --rm -v \
+            "$PWD/target:/target:Z" \
+            rustembedded/cross:${{ matrix.target }} \
+            aarch64-linux-gnu-strip \
+            /target/${{ matrix.target }}/release/$BIN_NAME1
+          docker run --rm -v \
+            "$PWD/target:/target:Z" \
+            rustembedded/cross:${{ matrix.target }} \
+            aarch64-linux-gnu-strip \
+            /target/${{ matrix.target }}/release/$BIN_NAME2
 
-        cp target/${{ matrix.target }}/release/sysit $stage/
-        cd $stage
+      - name: Build archive
+        shell: bash
+        run: |
+          mkdir dist
+          if [ "${{ matrix.os }}" = "windows-2019" ]; then
+            cp "target/${{ matrix.target }}/release/$BIN_NAME1.exe" "dist/"
+            cp "target/${{ matrix.target }}/release/$BIN_NAME2.exe" "dist/"
+          else
+            cp "target/${{ matrix.target }}/release/$BIN_NAME1" "dist/"
+            cp "target/${{ matrix.target }}/release/$BIN_NAME2" "dist/"
+          fi
 
-        RELEASE_VERSION=${GITHUB_REF#refs/tags/}
-        ASSET_NAME="sysit-$RELEASE_VERSION-${{ matrix.target }}.tar.gz"
-        ASSET_PATH="$src/$ASSET_NAME"
-        CHECKSUM_PATH="$ASSET_PATH.sha256"
+      - uses: actions/upload-artifact@v2.2.4
+        with:
+          name: bins-${{ matrix.build }}
+          path: dist
 
-        echo "ASSET_PATH=$ASSET_PATH" >> $GITHUB_ENV
-        echo "CHECKSUM_PATH=$CHECKSUM_PATH" >> $GITHUB_ENV
+  publish:
+    name: Publish
+    needs: [dist]
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout sources
+        uses: actions/checkout@v2
+        with:
+          submodules: false
 
-        tar czf $ASSET_PATH *
+      - uses: actions/download-artifact@v2
+        # with:
+        #   path: dist
+      # - run: ls -al ./dist
+      - run: ls -al bins-*
 
-        cd $src
+      - name: Calculate tag name
+        run: |
+          name=dev
+          if [[ $GITHUB_REF == refs/tags/v* ]]; then
+            name=${GITHUB_REF:10}
+          fi
+          echo ::set-output name=val::$name
+          echo TAG=$name >> $GITHUB_ENV
+        id: tagname
 
-        case $RUNNER_OS in
-            Linux)
-                sha256sum $ASSET_NAME > $CHECKSUM_PATH
-                ;;
-            macOS)
-                shasum -a 256 $ASSET_NAME > $CHECKSUM_PATH
-                ;;
-        esac
+      - name: Build archive
+        shell: bash
+        run: |
+          set -ex
 
+          rm -rf tmp
+          mkdir tmp
+          mkdir dist
 
-    - name: Release
-      uses: softprops/action-gh-release@v1
-      if: startsWith(github.ref, 'refs/tags/')
-      with:
-        files: |
-          ${{ env.ASSET_PATH }}
-          ${{ env.CHECKSUM_PATH }}
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          for dir in bins-* ; do
+              platform=${dir#"bins-"}
+              if [[ $platform =~ "windows" ]]; then
+                  exe=".exe"
+              fi
+              pkgname=$PROJECT_NAME-$TAG-$platform
+              mkdir tmp/$pkgname
+              # cp LICENSE README.md tmp/$pkgname
+              mv bins-$platform/$BIN_NAME1$exe tmp/$pkgname
+              mv bins-$platform/$BIN_NAME2$exe tmp/$pkgname
+              chmod +x tmp/$pkgname/$BIN_NAME1$exe
+              chmod +x tmp/$pkgname/$BIN_NAME2$exe
+
+              if [ "$exe" = "" ]; then
+                  tar cJf dist/$pkgname.tar.xz -C tmp $pkgname
+              else
+                  (cd tmp && 7z a -r ../dist/$pkgname.zip $pkgname)
+              fi
+          done
+
+      - name: Upload binaries to release
+        uses: svenstaro/upload-release-action@v2
+        with:
+          repo_token: ${{ secrets.GITHUB_TOKEN }}
+          file: dist/*
+          file_glob: true
+          tag: ${{ steps.tagname.outputs.val }}
+          overwrite: true
+
+      - name: Extract version
+        id: extract-version
+        run: |
+          printf "::set-output name=%s::%s\n" tag-name "${GITHUB_REF#refs/tags/}"
+
+      # - uses: mislav/bump-homebrew-formula-action@v1
+      #   with:
+      #     formula-path: ${{env.PROJECT_NAME}}.rb
+      #     homebrew-tap: ${{ env.BREW_TAP }}
+      #     download-url: "https://github.com/${{ env.REPO_NAME }}/releases/download/${{ steps.extract-version.outputs.tag-name }}/${{env.PROJECT_NAME}}-${{ steps.extract-version.outputs.tag-name }}-x86_64-macos.tar.xz"
+      #     commit-message: updating formula for ${{ env.PROJECT_NAME }}
+      #   env:
+      #     COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
+      #
+      # you can use this initial file in your homebrew-tap if you don't have an initial formula:
+      # <projectname>.rb
+      #
+      # class <Projectname capitalized> < Formula
+      #   desc "A test formula"
+      #   homepage "http://www.example.com"
+      #   url "-----"
+      #   version "-----"
+      #   sha256 "-----"
+
+      #   def install
+      #     bin.install "<bin-name>"
+      #   end
+      # end
